urls.py
from django.conf.urls import url

import tournament.views as views

urlpatterns = [
	url(r'^$', views.LatestTournamentDetailView.as_view(), name="latest-tournament"), 
	url(r'^(?P<slug>\w+)$', views.TournamentDetailView.as_view(), name="tournament-detail"),
	url(r'^register/(?P<slug>\w+)$', views.RegisterParticipantView.as_view(), name="register-participant"),
	url(r'^active/(?P<slug>\w+)$', views.ActiveGamesListView.as_view(), name="tournament-active-games"),
	url(r'^finished/(?P<slug>\w+)$', views.FinishedGamesListView.as_view(), name="tournament-finished-games"),
]

models.py
import os.path

import logging
logger = logging.getLogger(__name__)
import random

from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.utils.text import slugify
from django.utils.translation import ugettext_lazy as _

from transmeta import TransMeta

import condottieri_scenarios.models as scenarios
import machiavelli.models as machiavelli

class Tournament(models.Model, metaclass=TransMeta):
	slug = models.SlugField(_("slug"), max_length=20, unique=True)
	created_on = models.DateTimeField(_("created on"), auto_now_add=True)
	deadline = models.DateTimeField(_("registration deadline"))
	admission_open = models.BooleanField(_("admission is open"), default=False)
	auto_accept = models.BooleanField(_("automatically accept participants"), default=False)
	minimum_users = models.PositiveIntegerField(_("minimum users"), default=0)
	title = models.CharField(_("title"), max_length=100)
	description = models.TextField(_("description"))
	prize = models.TextField(_("prize"))
	rules = models.URLField(_("rules"))
	sponsors = models.ManyToManyField('Sponsor', blank=True)
	created_by = models.ForeignKey(User, on_delete=models.CASCADE)

	class Meta:
		verbose_name = _("tournament")
		verbose_name_plural = _("tournaments")
		ordering = ["created_on",]
		translate = ('title', 'description', 'prize', 'rules')

	def __str__(self):
		return self.slug

	def extend_deadline(self):
		"""
		When there are fewer participants than the minimum, extend the admission deadline
		"""
		self.deadline = self.deadline + datetime.timedelta(seconds=24*60*60)
		self.save()
		logger.info("Extended tournament deadline.")

def get_banner_upload_path(instance, filename):
	return os.path.join(settings.MEDIA_ROOT, "banners", instance.banner_filename)

class Sponsor(models.Model):
	name = models.CharField(_("name"), max_length=100)
	motto = models.CharField(_("motto"), max_length=200)
	banner = models.ImageField(_("banner"), upload_to=get_banner_upload_path)
	url = models.URLField()

	class Meta:
		verbose_name = _("sponsor")
		verbose_name_plural = _("sponsors")

	def __str__(self):
		return self.name

	def _get_banner_filename(self):
		return "%s.png" % slugify(self.name)

	banner_filename = property(_get_banner_filename)

class Participant(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
	joined_on = models.DateTimeField(_("joined_on"), auto_now_add=True)
	accepted = models.BooleanField(_("accepted"), default=False)
	eliminated = models.BooleanField(_("eliminated"), default=False)

	class Meta:
		verbose_name = _("participant")
		verbose_name_plural = _("participants")
		unique_together = (("user", "tournament"),)

	def __str__(self):
		return str(self.user)

	def save(self, *args, **kwargs):
		if not self.pk:
			if self.tournament.auto_accept:
				self.accepted = True
		super(Participant, self).save(*args, **kwargs)

class Stage(models.Model):
	tournament = models.ForeignKey(Tournament, on_delete=models.CASCADE)
	number = models.PositiveIntegerField(_("number"), default=0)
	size = models.PositiveIntegerField(_("size"), default=0)
	number_of_games = models.PositiveIntegerField(_("number of games"), default=0)
	started_on = models.DateTimeField(_("started on"), null=True, blank=True)
	finished_on = models.DateTimeField(_("finished on"), null=True, blank=True)	
	scenario = models.ForeignKey(scenarios.Scenario, on_delete=models.CASCADE)
	time_limit = models.PositiveIntegerField(_("time limit"), default=24*60*60,
		help_text = _("seconds available to play a turn"))
	cities_to_win = models.PositiveIntegerField(_("cities to win"), default=15,
		help_text=_("cities that must be controlled to win a game"))
	years_limit = models.PositiveIntegerField(_("years limit"), default=0,
		help_text=_("the game finish after these years"))
	users = models.ManyToManyField(User, through="Slot") 
	
	class Meta:
		verbose_name = _("stage")
		verbose_name_plural = _("stages")
		unique_together = (("tournament", "number"),)

	def __str__(self):
		return _("Stage %s in %s") % (self.number, self.tournament.title)

	def create_slots(self):
		""" Creates a new slot in this stage for all the tournament participants that has not
		been eliminated."""
		participants = self.tournament.participant_set.filter(accepted=True, eliminated=False)
		for p in participants:
			slot = Slot(user=p.user, stage=self)
			slot.save()
			logger.info("Added slot for %s" % p.user)

	def create_empty_games(self):
		for i in range (0, self.number_of_games):
			title = "%s-%s-%s" % (self.tournament.slug, self.number, i)
			g = TournamentGame(title=title, stage=self)
			g.save()

	#def create_games(self):
	#	player_list_size = self.number_of_games * self.scenario.number_of_players
	#	base_list = list(self.users.all())

		
	
class Configuration(models.Model):
	""" Defines the common configuration options for each game in a stage. 
	"""

	stage = models.OneToOneField(Stage, verbose_name=_('stage'), editable=False, on_delete=models.CASCADE)
	finances = models.BooleanField(_('finances'), default=False)
	assassinations = models.BooleanField(_('assassinations'), default=False,
					help_text=_('will enable Finances'))
	excommunication = models.BooleanField(_('excommunication'), default=False)
	special_units = models.BooleanField(_('special units'), default=False,
					help_text=_('will enable Finances'))
	lenders = models.BooleanField(_('money lenders'), default=False,
					help_text=_('will enable Finances'))
	unbalanced_loans = models.BooleanField(_('unbalanced loans'), default=False,
		help_text=_('the credit for all players will be 25d'))
	conquering = models.BooleanField(_('conquering'), default=False)
	famine = models.BooleanField(_('famine'), default=False)
	plague = models.BooleanField(_('plague'), default=False)
	storms = models.BooleanField(_('storms'), default=False)
	strategic = models.BooleanField(_('strategic movement'), default=False)
	variable_home = models.BooleanField(_('variable home country'), default=False, help_text=_('conquering will be disabled'))
	taxation = models.BooleanField(_('taxation'), default=False,
					help_text=_('will enable Finances and Famine'))
	fow = models.BooleanField(_('fog of war'), default=False,
		help_text=_('each player sees only what happens near his borders'))
	press = models.PositiveIntegerField(_('press'), choices=machiavelli.PRESS_TYPES, default=0)

	def __str__(self):
		return _("Configuration for %s") % self.stage

	def get_enabled_rules(self):
		rules = []
		for f in self._meta.fields:
			if isinstance(f, models.BooleanField):
				if f.value_from_object(self):
					rules.append(str(f.verbose_name))
		return rules

	def _get_gossip(self):
		if self.press in (0, 2):
			return True
		return False

	gossip = property(_get_gossip)

	def _get_letters(self):
		return self.press == 0

	letters = property(_get_letters)

	def _get_public_gossip(self):
		return self.press == 2

	public_gossip = property(_get_public_gossip)
	
#def create_configuration(sender, instance, created, **kwargs):
#    if isinstance(instance, Stage) and created:
#		config = Configuration(stage=instance)
#		config.save()
#
#models.signals.post_save.connect(create_configuration, sender=Stage)

class Slot(models.Model):
	""" A Slot defines the participation of a User in a Stage.
	"""
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	stage = models.ForeignKey(Stage, on_delete=models.CASCADE)
	score = models.PositiveIntegerField(_("score"), blank=True, null=True)

	class Meta:
		verbose_name = _("slot")
		verbose_name_plural = _("slots")
		unique_together = (("user", "stage"),)

	def __str__(self):
		return str(self.user)

class TournamentGame(machiavelli.Game):
	stage = models.ForeignKey(Stage, on_delete=models.CASCADE)

	class Meta:
		verbose_name = _("tournament game")
		verbose_name_plural = _("tournament games")
	
	def save(self, *args, **kwargs):
		""" Fill some properties common to tournament games """
		if not self.pk:
			s = self.stage
			self.slots = 0
			self.scenario = s.scenario
			self.created_by = s.tournament.created_by
			self.visible = False
			self.time_limit = s.time_limit
			self.autostart = True
			self.cities_to_win = s.cities_to_win
			self.years_limit = s.years_limit
			self.fast = False
			self.uses_karma = False
			self.private = False
		super(TournamentGame, self).save(*args, **kwargs)
	
	def check_revolution(self):
		""" Override machiavelli.Game.check_revolution. Revolutions are not applied in
		tournament games. """
		return False
	
def configure_game(sender, instance, created=False, **kwargs):
	"""
	Creates a Configuration object for the new game
	"""
	if created:
		s = instance.stage
		config = machiavelli.Configuration(game=instance)
		config.finances = s.configuration.finances
		config.assassination = s.configuration.assassinations
		config.excommunication = s.configuration.excommunication
		config.special_units = s.configuration.special_units
		config.lenders = s.configuration.lenders
		config.unbalanced_loans = s.configuration.unbalanced_loans
		config.conquering = s.configuration.conquering
		config.famine = s.configuration.famine
		config.plague = s.configuration.plague
		config.storms = s.configuration.storms
		config.strategic = s.configuration.strategic
		config.press = s.configuration.press
		config.save()

models.signals.post_save.connect(configure_game, sender=TournamentGame)

templates/tournament/base.html
{% extends 'site_base.html' %}

{% load i18n %}

{% block extra_head %}
<link rel="stylesheet" href="{{ STATIC_URL }}tournament/css/tournament.css" />
{% endblock %}

{% block subnav %}{% endblock %}

{% block main_content %}{% endblock %}

{% block sidebar %}
<div id="sponsors">
<h2>{% blocktrans %}Sponsors{% endblocktrans %}</h2>

<p>{% blocktrans %}This tournament is possible thanks to the help of our sponsors.{% endblocktrans %}

{% for sponsor in tournament.sponsors.all %}
<div class="sponsor">
<a href="{{ sponsor.url}}" title="{{ sponsor.motto }}"><img src="{{ MEDIA_URL }}banners/{{ sponsor.banner_filename }}" alt="{{ sponsor.motto }}"/></a></p>
</div>
{% endfor %}

</div>

{% block extra_sidebar %}{% endblock %}


{% endblock %}

templates/tournament/game_list_active.html
{% extends "tournament/base.html" %}

{% load i18n %}
{% load machiavelli_tags %}
{% load condottieri_profiles_tags %}

{% block head_title %}
{% blocktrans with tournament.title as title %}Active games in {{title}}{% endblocktrans %}
{% endblock %}

{% block main_content %}
<h1>{% blocktrans with tournament.title as title %}Active games in {{title}}{% endblocktrans %}</h1>
{% if not game_list %}
	<p>{% blocktrans %}At this moment there are no active games in this tournament.{% endblocktrans %}</p>
{% else %}
	<p>{% blocktrans %}These are all the active games in the tournament.{% endblocktrans %}</p>

{% for game in game_list %}
<div class="game_info {% if game.fast %}fast{% endif %}">
<h2><span><a href="{{ game.get_absolute_url }}">{{ game.title }}</a></span></h2>
<div class="map">
<img src="{{ game.thumbnail_url }}" />
</div>
{% if game.started %}
<div class="time">
{% blocktrans with game.started|timesince as time %}Started {{ time }} ago{% endblocktrans %}
</div>
{% endif %}
<dl>
<dt>{% trans "Average score" %}</dt><dd>{{ game.get_average_score|score_stars }}</dd>
<dt>{% trans "Average karma" %}</dt><dd>{{ game.get_average_karma|karma_stars }}</dd>
<dt>{% trans "Scenario" %}</dt><dd><a href="{% url "scenario_detail" game.scenario.name %}">{{ game.scenario.title }}</a></dd>
<dt>{% trans "Cities to win" %}</dt><dd>{{ game.cities_to_win }}</dd>
<dt>{% trans "Time limit" %}</dt><dd>{{ game.get_time_limit_display }}</dd>
<dt>{% trans "Turn" %}</dt><dd>{{ game.get_season_display }}, {{ game.year }} - {{ game.get_phase_display }}</dd>
<dt>{% trans "Players" %}</dt>
<dd>
	{% if game.visible %}
	<ul>
	{% for p in game.player_set.all %}
		{% if p.user %}
		<li><a href="{% url "profile_detail" username=p.user.username %}">{{ p.user.username }}</a></li>
		{% endif %}
	{% endfor %}
	</ul>
	{% else %}
	{% trans "Players are not visible" %}
	{% endif %}
</dd>
{% if game.comment %}
<dt>{% trans "Comment" %}</dt>
<dd>{{ game.comment }}</dd>
{% endif %}
</dl>
<ul class="section_menu">
	<li>{% trans "Version" %}: {{ game.version }}</li>
	<li>{% rule_icons game.configuration %}</li>
	<li><a href="{% url "show-game" game.slug %}">{% trans "View game" %}</a></li>
	<li><a href="{% url "game-log" game.slug %}">{% trans "Log" %}</a></li> 
</ul>
</div>
{% endfor %}

<div class="pagination">
	<span class="step-links">
		{% if page_obj.has_previous %}
			<a href="?page={{ page_obj.previous_page_number }}">&lt;&lt;</a>
		{% endif %}
		
		<span class="current">
			{% trans "Page" %} {{ page_obj.number }} {% trans "of" %} {{ page_obj.paginator.num_pages }}.
		</span>

		{% if page_obj.has_next %}
			<a href="?page={{ page_obj.next_page_number }}">&gt;&gt;</a>
		{% endif %}
	</span>
</div>

{% endif %}

<p><a href="{% url "tournament-detail" tournament.slug %}">{% trans "Return to tournament" %}</a></p>
{% endblock %}

templates/tournament/game_list_finished.html
{% extends "tournament/base.html" %}

{% load i18n %}
{% load machiavelli_tags %}

{% block head_title %}
{% blocktrans with tournament.title as title %}Finished games in {{title}}{% endblocktrans %}
{% endblock %}

{% block main_content %}
<h1>{% blocktrans with tournament.title as title %}Finished games in {{title}}{% endblocktrans %}</h1>

{% for game in game_list %}
<div class="game_info">
<h2><span><a href="{{ game.get_absolute_url }}">{{ game.title }}</a></span></h2>
<div class="map">
<img src="{{ game.thumbnail_url }}" />
</div>
{% if game.started and game.finished %}
<div class="time">
{% blocktrans with game.finished|date:"SHORT_DATE_FORMAT" as finished and game.finished|timeuntil:game.started as time %}
Finished on {{ finished }} after {{ time }}.{% endblocktrans %}
</div>
{% endif %}
<dl>
<dt>{% trans "Scenario" %}</dt><dd><a href="{% url "scenario_detail" game.scenario.name %}">{{ game.scenario.title }}</a></dd>
<dt>{% trans "Cities to win" %}</dt><dd>{{ game.cities_to_win }}</dd>
<dt>{% trans "Players" %}</dt>
<dd>
	<ul>
	{% for s in game.score_set.all %}
		<li><a href="{% url "profile_detail" username=s.user.username %}">{{ s.user.username }}</a> ({{ s.points }})</li>
	{% endfor %}
	</ul>
</dd>
<dt>{% trans "Winner" %}</dt>
{% for w in game.winners_qs %}
<dd><a href="{% url "profile_detail" username=w.user.username %}">{{ w.user }}</a></dd>
{% endfor %}
</dl>
<ul class="section_menu">
	<li>{% trans "Version" %}: {{ game.version }}</li>
	<li>{{ game.comments_count }} {% trans "comments" %}</li>
	<li>{% rule_icons game.configuration %}</li>
	<li><a href="{% url "show-game" game.slug %}">{% trans "View scores" %}</a></li>
</ul>
</div>
{% endfor %}

<div class="pagination">
	<span class="step-links">
		{% if page_obj.has_previous %}
			<a href="?page={{ page_obj.previous_page_number }}">&lt;&lt;</a>
		{% endif %}
		
		<span class="current">
			{% trans "Page" %} {{ page_obj.number }} {% trans "of" %} {{ page_obj.paginator.num_pages }}.
		</span>

		{% if page_obj.has_next %}
			<a href="?page={{ page_obj.next_page_number }}">&gt;&gt;</a>
		{% endif %}
	</span>
</div>
<p><a href="{% url "tournament-detail" tournament.slug %}">{% trans "Return to tournament" %}</a></p>
{% endblock %}

templates/tournament/register.html
{% extends 'tournament/base.html' %}

{% load i18n %}

{% block head_title %}{{ tournament.title }}{% endblock %}


{% block main_content %}
<p>{{ message }}</p>
<p><a href="{% url "tournament-detail" tournament.slug %}">{% trans "Return to the tournament." %}</a></p>
{% endblock %}

templates/tournament/tournament_detail.html
{% extends 'tournament/base.html' %}

{% load i18n %}
{% load avatar_tags %}

{% block head_title %}{{ tournament.title }}{% endblock %}


{% block main_content %}

<h1>{{ tournament.title }}</h1>

<div id="tournament_description">
{{ tournament.description|safe|linebreaks }}
</div>

<h2>{% trans "Prizes" %}</h2>

<div id="tournament_prize">
{{ tournament.prize|safe|linebreaks }}
</div>

<h2>{% trans "Rules" %}</h2>
<div id="tournament_rules">
<p>{% blocktrans %}Registration in the tournament implies the acceptance of its rules, available in the link below. Before registering, be sure to read these rules carefully. If you have any doubts, you can use the forum to resolve them.{% endblocktrans %}</p>

<p>{% blocktrans %}The organization reserves the right to make changes in the tournament system at any time.{% endblocktrans %}</p>

<p><a href="{{ tournament.rules }}">{% trans "Tournament rules" %}</a></p>

</div>

<h2>{% trans "Registration" %}</h2>
<div id="tournament_registration">
{% if tournament.admission_open %}

<p>{% blocktrans with tournament.deadline as deadline %}Admission to the tournament is open until {{ deadline }}.{% endblocktrans %}</p>

<p>{% blocktrans %}By clicking the following link you will register in the tournament and you accept the tournament rules. Please, keep in mind that registration cannot be undone.{% endblocktrans %}</p>

<p><a href="{% url "register-participant" tournament.slug %}">{% blocktrans %}Register me in the tournament.{% endblocktrans %}</a></p>


{% else %}
<p>{% blocktrans %}Admission to the tournament is closed.{% endblocktrans %}
{% endif %}
</div>

<h2>{% trans "Participants" %}</h2>
<div id="tournament_participants">
<ul>
{% for p in tournament.participant_set.all %}
	<li {% if p.eliminated %}class="eliminated"{% endif %}><a href="{% url "profile_detail" p.user.username %}">{% avatar p.user 24 %} {{ p }}</a></li>
{% endfor %}
</ul>
</div>


{% endblock %}

{% block extra_sidebar %}


<div>
<h2>{% blocktrans %}Current stage{% endblocktrans %}</h2>
{% if current_stage %}
	<p>{% blocktrans with current_stage.number as number %}The stage "{{number}}" is being played.{% endblocktrans %}</p>
{% else %}
	<p>{% blocktrans %}The tournament is not being played.{% endblocktrans %}</p>
{% endif %}

<h2>{% blocktrans %}Tournament games{% endblocktrans %}</h2>
<p><a href="{% url "tournament-active-games" tournament.slug %}">{% trans "Active games" %}</a></p>
<p><a href="{% url "tournament-finished-games" tournament.slug %}">{% trans "Finished games" %}</a></p>
</div>

{% endblock %}